USE lavidaloca;

ALTER TABLE users
  ADD COLUMN xp INT DEFAULT 0,
  ADD COLUMN energy INT DEFAULT 100,
  ADD COLUMN max_energy INT DEFAULT 100,
  ADD COLUMN health INT DEFAULT 100,
  ADD COLUMN max_health INT DEFAULT 100,
  ADD COLUMN crimes_done INT DEFAULT 0,
  ADD COLUMN energy_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN last_crime TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS activity_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX (user_id)
);